/*
 * 秋招资源汇总平台的初始化数据。
 *
 * 日期和招聘信息均为演示数据，不代表企业真实招聘安排。应用加载后应
 * 复制此数组再写入 localStorage，避免直接修改初始化常量影响重置逻辑。
 */

const RECRUITMENT_STATUS_OPTIONS = [
  "未投递",
  "已投递",
  "筛选中",
  "笔试 / 测评中",
  "面试中",
  "已发 offer",
  "终止流程 / 已淘汰",
  "已接受 / 已拒绝 offer",
];

const RECRUITMENT_COMPANY_TYPES = ["央国企", "私企", "外企", "事业单位", "其他"];

const RECRUITMENT_DATA_META = {
  isDemo: true,
  dateNote: "开放时间与截止时间为模拟的 2026 秋招日期，请以企业官方页面为准。",
  storageKey: "autumn-recruitment-tracker:v1",
  schemaVersion: 1,
};

const INITIAL_RECRUITMENT_DATA = [
  {
    id: "recruitment-001",
    companyName: "国家电网",
    companyType: "央国企",
    openDate: "2026-08-18",
    deadline: "2026-09-04",
    province: "北京",
    city: "北京",
    categories: ["电气工程", "电力系统", "信息技术", "综合管理"],
    campusUrl: "https://zhaopin.sgcc.com.cn/",
    status: "未投递",
    statusUpdatedAt: "2026-08-31T09:00:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-002",
    companyName: "中石油",
    companyType: "央国企",
    openDate: "2026-08-25",
    deadline: "2026-09-12",
    province: "北京",
    city: "北京",
    categories: ["石油工程", "化学工程", "机械工程", "综合管理"],
    campusUrl: "https://job.cnpc.com.cn/",
    status: "已投递",
    statusUpdatedAt: "2026-08-30T14:20:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-003",
    companyName: "中国移动",
    companyType: "央国企",
    openDate: "2026-08-20",
    deadline: "2026-09-03",
    province: "北京",
    city: "北京",
    categories: ["通信工程", "计算机", "产品运营", "市场营销"],
    campusUrl: "https://job.10086.cn/",
    status: "筛选中",
    statusUpdatedAt: "2026-08-29T10:15:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-004",
    companyName: "中国建筑",
    companyType: "央国企",
    openDate: "2026-08-27",
    deadline: "2026-09-18",
    province: "北京",
    city: "北京",
    categories: ["工程管理", "土木工程", "建筑设计", "财务管理"],
    campusUrl: "https://job.cscec.com/",
    status: "笔试 / 测评中",
    statusUpdatedAt: "2026-08-31T16:40:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-005",
    companyName: "华润集团",
    companyType: "央国企",
    openDate: "2026-08-15",
    deadline: "2026-09-10",
    province: "广东",
    city: "深圳",
    categories: ["战略投资", "商业管理", "医药健康", "信息技术"],
    campusUrl: "https://campus.crc.com.cn/",
    status: "面试中",
    statusUpdatedAt: "2026-08-28T18:10:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-006",
    companyName: "中国石化",
    companyType: "央国企",
    openDate: "2026-08-22",
    deadline: "2026-09-25",
    province: "北京",
    city: "北京",
    categories: ["化工技术", "炼化工程", "新能源", "财务审计"],
    campusUrl: "https://job.sinopec.com/",
    status: "已发 offer",
    statusUpdatedAt: "2026-08-27T11:30:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-007",
    companyName: "中国海油",
    companyType: "央国企",
    openDate: "2026-09-01",
    deadline: "2026-10-08",
    province: "北京",
    city: "北京",
    categories: ["海洋工程", "石油工程", "安全环保", "法务管理"],
    campusUrl: "https://job.cnooc.com.cn/",
    status: "终止流程 / 已淘汰",
    statusUpdatedAt: "2026-08-31T13:05:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-008",
    companyName: "南方电网",
    companyType: "央国企",
    openDate: "2026-08-28",
    deadline: "2026-09-20",
    province: "广东",
    city: "广州",
    categories: ["电气工程", "数字化技术", "调度运行", "人力资源"],
    campusUrl: "https://zhaopin.csg.cn/",
    status: "已接受 / 已拒绝 offer",
    statusUpdatedAt: "2026-08-26T09:45:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-009",
    companyName: "中国中铁",
    companyType: "央国企",
    openDate: "2026-09-01",
    deadline: "2026-10-12",
    province: "北京",
    city: "北京",
    categories: ["工程技术", "轨道交通", "项目管理", "商务合约"],
    campusUrl: "https://job.crec.cn/",
    status: "未投递",
    statusUpdatedAt: "2026-08-31T09:10:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-010",
    companyName: "国家能源集团",
    companyType: "央国企",
    openDate: "2026-08-19",
    deadline: "2026-09-28",
    province: "北京",
    city: "北京",
    categories: ["能源动力", "采矿工程", "智能制造", "经济管理"],
    campusUrl: "https://zhaopin.chnenergy.com.cn/",
    status: "已投递",
    statusUpdatedAt: "2026-08-31T15:00:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-011",
    companyName: "腾讯",
    companyType: "私企",
    openDate: "2026-08-24",
    deadline: "2026-10-31",
    province: "广东",
    city: "深圳",
    categories: ["软件开发", "产品经理", "游戏研发", "设计"],
    campusUrl: "https://join.qq.com/",
    status: "筛选中",
    statusUpdatedAt: "2026-08-30T10:00:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-012",
    companyName: "字节跳动",
    companyType: "私企",
    openDate: "2026-08-18",
    deadline: "2026-10-15",
    province: "北京",
    city: "北京",
    categories: ["后端开发", "算法", "产品运营", "内容策略"],
    campusUrl: "https://jobs.bytedance.com/campus/",
    status: "笔试 / 测评中",
    statusUpdatedAt: "2026-08-29T20:25:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-013",
    companyName: "华为",
    companyType: "私企",
    openDate: "2026-08-12",
    deadline: "2026-10-20",
    province: "广东",
    city: "深圳",
    categories: ["软件开发", "芯片与器件", "通信技术", "销售管理"],
    campusUrl: "https://career.huawei.com/reccampportal/portal5/index.html",
    status: "面试中",
    statusUpdatedAt: "2026-08-31T18:00:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-014",
    companyName: "美团",
    companyType: "私企",
    openDate: "2026-08-26",
    deadline: "2026-09-30",
    province: "北京",
    city: "北京",
    categories: ["软件开发", "数据分析", "产品经理", "商业分析"],
    campusUrl: "https://campus.meituan.com/",
    status: "已发 offer",
    statusUpdatedAt: "2026-08-28T16:00:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-015",
    companyName: "京东",
    companyType: "私企",
    openDate: "2026-08-21",
    deadline: "2026-09-16",
    province: "北京",
    city: "北京",
    categories: ["供应链管理", "软件开发", "物流运营", "产品运营"],
    campusUrl: "https://campus.jd.com/",
    status: "未投递",
    statusUpdatedAt: "2026-08-31T08:30:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-016",
    companyName: "比亚迪",
    companyType: "私企",
    openDate: "2026-08-17",
    deadline: "2026-10-10",
    province: "广东",
    city: "深圳",
    categories: ["车辆工程", "电池研发", "智能驾驶", "制造工程"],
    campusUrl: "https://job.byd.com/",
    status: "已投递",
    statusUpdatedAt: "2026-08-30T12:40:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-017",
    companyName: "阿里巴巴",
    companyType: "私企",
    openDate: "2026-08-29",
    deadline: "2026-10-18",
    province: "浙江",
    city: "杭州",
    categories: ["软件开发", "算法", "产品经理", "用户研究"],
    campusUrl: "https://campus.alibaba.com/",
    status: "筛选中",
    statusUpdatedAt: "2026-08-31T19:15:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-018",
    companyName: "小米",
    companyType: "私企",
    openDate: "2026-08-25",
    deadline: "2026-09-22",
    province: "北京",
    city: "北京",
    categories: ["嵌入式开发", "互联网产品", "工业设计", "市场营销"],
    campusUrl: "https://hr.xiaomi.com/",
    status: "未投递",
    statusUpdatedAt: "2026-08-31T08:50:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-019",
    companyName: "宁德时代",
    companyType: "私企",
    openDate: "2026-09-01",
    deadline: "2026-09-08",
    province: "福建",
    city: "宁德",
    categories: ["电化学", "材料研发", "电气工程", "质量工程"],
    campusUrl: "https://hr.catl.com/",
    status: "笔试 / 测评中",
    statusUpdatedAt: "2026-08-31T17:20:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-020",
    companyName: "拼多多",
    companyType: "私企",
    openDate: "2026-08-30",
    deadline: "2026-10-05",
    province: "上海",
    city: "上海",
    categories: ["后端开发", "算法", "数据产品", "运营管理"],
    campusUrl: "https://jobs.pinduoduo.com/",
    status: "未投递",
    statusUpdatedAt: "2026-08-31T09:25:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-021",
    companyName: "西门子",
    companyType: "外企",
    openDate: "2026-08-20",
    deadline: "2026-09-26",
    province: "北京",
    city: "北京",
    categories: ["自动化工程", "数字化工业", "项目管理", "销售工程"],
    campusUrl: "https://www.siemens.com/cn/zh/company/jobs.html",
    status: "已投递",
    statusUpdatedAt: "2026-08-30T09:10:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-022",
    companyName: "博世",
    companyType: "外企",
    openDate: "2026-08-23",
    deadline: "2026-10-14",
    province: "上海",
    city: "上海",
    categories: ["汽车电子", "软件开发", "机械工程", "供应链"],
    campusUrl: "https://www.bosch.com.cn/careers/",
    status: "筛选中",
    statusUpdatedAt: "2026-08-31T10:35:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-023",
    companyName: "麦肯锡",
    companyType: "外企",
    openDate: "2026-09-01",
    deadline: "2026-09-29",
    province: "上海",
    city: "上海",
    categories: ["管理咨询", "商业分析", "数字化咨询"],
    campusUrl: "https://www.mckinsey.com.cn/careers/",
    status: "未投递",
    statusUpdatedAt: "2026-08-31T11:00:00+08:00",
    isDemo: true,
  },
  {
    id: "recruitment-024",
    companyName: "联合利华",
    companyType: "外企",
    openDate: "2026-08-28",
    deadline: "2026-10-07",
    province: "上海",
    city: "上海",
    categories: ["管理培训生", "市场营销", "供应链", "财务"],
    campusUrl: "https://careers.unilever.com/china/",
    status: "已投递",
    statusUpdatedAt: "2026-08-30T13:50:00+08:00",
    isDemo: true,
  },
];

// 兼容浏览器直接引入和 Node 校验/构建脚本，不依赖 window、document 等对象。
globalThis.INITIAL_RECRUITMENT_DATA = INITIAL_RECRUITMENT_DATA;
globalThis.RECRUITMENT_STATUS_OPTIONS = RECRUITMENT_STATUS_OPTIONS;
globalThis.RECRUITMENT_COMPANY_TYPES = RECRUITMENT_COMPANY_TYPES;
globalThis.RECRUITMENT_DATA_META = RECRUITMENT_DATA_META;

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    INITIAL_RECRUITMENT_DATA,
    RECRUITMENT_STATUS_OPTIONS,
    RECRUITMENT_COMPANY_TYPES,
    RECRUITMENT_DATA_META,
  };
}
